<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:decision="http://www.bonitasoft.org/ns/bpm/process/decision" xmlns:expression="http://www.bonitasoft.org/ns/bpm/expression" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.3/notation" xmlns:process="http://www.bonitasoft.org/ns/bpm/process">
  <process:MainProcess xmi:id="_Ko-xgFcBEfG-WqRER0mjbQ" name="DiagramaSolicitudVacaciones" bonitaModelVersion="8">
    <elements xmi:type="process:Pool" xmi:id="_Ko-xgVcBEfG-WqRER0mjbQ" name="Pool">
      <elements xmi:type="process:Lane" xmi:id="_Ko-xglcBEfG-WqRER0mjbQ" name="Empleado (lane) " actor="_Ko-xm1cBEfG-WqRER0mjbQ">
        <elements xmi:type="process:StartEvent" xmi:id="_Ko-xg1cBEfG-WqRER0mjbQ" name="IniIngresar solicitud" outgoing="_Ko-xmFcBEfG-WqRER0mjbQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Ko-xhFcBEfG-WqRER0mjbQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Ko-xhVcBEfG-WqRER0mjbQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Ko-xhlcBEfG-WqRER0mjbQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_Ko-xh1cBEfG-WqRER0mjbQ" name="Validar solicitud" outgoing="_KAdjgFcCEfG-WqRER0mjbQ" incoming="_Ko-xmFcBEfG-WqRER0mjbQ" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Ko-xiFcBEfG-WqRER0mjbQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Ko-xiVcBEfG-WqRER0mjbQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Ko-xilcBEfG-WqRER0mjbQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_Ko-xi1cBEfG-WqRER0mjbQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_Ko-xjFcBEfG-WqRER0mjbQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_Ko-xjVcBEfG-WqRER0mjbQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_Ko-xjlcBEfG-WqRER0mjbQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_Ko-xj1cBEfG-WqRER0mjbQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_Ko-xkFcBEfG-WqRER0mjbQ">
            <targetForm xmi:type="expression:Expression" xmi:id="_DqVYUFhJEfGWWfrtXK2Gmw" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_Ko-xklcBEfG-WqRER0mjbQ"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_Ko-xk1cBEfG-WqRER0mjbQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_LVmxgFcCEfG-WqRER0mjbQ" name="¿Solicitud aprobada?" outgoing="_Zoav0FcCEfG-WqRER0mjbQ _eEhuwFcCEfG-WqRER0mjbQ" incoming="_KAdjgFcCEfG-WqRER0mjbQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_KAVnsVcCEfG-WqRER0mjbQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_KAVnsFcCEfG-WqRER0mjbQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_KAVnslcCEfG-WqRER0mjbQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_ZoY6oFcCEfG-WqRER0mjbQ" name="Notificar aprobación" outgoing="_m9Pb4FcCEfG-WqRER0mjbQ" incoming="_Zoav0FcCEfG-WqRER0mjbQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_ZoZhsVcCEfG-WqRER0mjbQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_ZoZhsFcCEfG-WqRER0mjbQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_ZoZhslcCEfG-WqRER0mjbQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_ZoZhs1cCEfG-WqRER0mjbQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_ZoZhtFcCEfG-WqRER0mjbQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_ZoZhtVcCEfG-WqRER0mjbQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_ZoZht1cCEfG-WqRER0mjbQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_ZoZhtlcCEfG-WqRER0mjbQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_eEZy8FcCEfG-WqRER0mjbQ" name="Notificar rechazo" outgoing="_tT_GFFcDEfG-WqRER0mjbQ" incoming="_eEhuwFcCEfG-WqRER0mjbQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_eEhHsVcCEfG-WqRER0mjbQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_eEhHsFcCEfG-WqRER0mjbQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_eEhHslcCEfG-WqRER0mjbQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_eEhHs1cCEfG-WqRER0mjbQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_eEhHtFcCEfG-WqRER0mjbQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_eEhHtVcCEfG-WqRER0mjbQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_eEhHt1cCEfG-WqRER0mjbQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_eEhHtlcCEfG-WqRER0mjbQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_m9LKcFcCEfG-WqRER0mjbQ" name="Fin - Solicitud aprobada" incoming="_m9Pb4FcCEfG-WqRER0mjbQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_m9LKclcCEfG-WqRER0mjbQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_m9LKcVcCEfG-WqRER0mjbQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_m9LKc1cCEfG-WqRER0mjbQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_tT-fAFcDEfG-WqRER0mjbQ" name="Fin - Solicitud rechazada" incoming="_tT_GFFcDEfG-WqRER0mjbQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_tT-fAlcDEfG-WqRER0mjbQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_tT-fAVcDEfG-WqRER0mjbQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_tT-fA1cDEfG-WqRER0mjbQ" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <formMapping xmi:type="process:FormMapping" xmi:id="_Ko-xlFcBEfG-WqRER0mjbQ">
        <targetForm xmi:type="expression:Expression" xmi:id="_DqVYUVhJEfGWWfrtXK2Gmw" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_Ko-xllcBEfG-WqRER0mjbQ">
        <targetForm xmi:type="expression:Expression" xmi:id="_Ko-xl1cBEfG-WqRER0mjbQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Ko-xmFcBEfG-WqRER0mjbQ" target="_Ko-xh1cBEfG-WqRER0mjbQ" source="_Ko-xg1cBEfG-WqRER0mjbQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Ko-xmVcBEfG-WqRER0mjbQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_Ko-xmlcBEfG-WqRER0mjbQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_KAdjgFcCEfG-WqRER0mjbQ" target="_LVmxgFcCEfG-WqRER0mjbQ" source="_Ko-xh1cBEfG-WqRER0mjbQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_KAdjgVcCEfG-WqRER0mjbQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_KAdjglcCEfG-WqRER0mjbQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Zoav0FcCEfG-WqRER0mjbQ" name="si" target="_ZoY6oFcCEfG-WqRER0mjbQ" source="_LVmxgFcCEfG-WqRER0mjbQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Zoav0VcCEfG-WqRER0mjbQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_Zoav0lcCEfG-WqRER0mjbQ" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_eEhuwFcCEfG-WqRER0mjbQ" name="No" target="_eEZy8FcCEfG-WqRER0mjbQ" source="_LVmxgFcCEfG-WqRER0mjbQ" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_eEhuwVcCEfG-WqRER0mjbQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_eEhuwlcCEfG-WqRER0mjbQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_m9Pb4FcCEfG-WqRER0mjbQ" target="_m9LKcFcCEfG-WqRER0mjbQ" source="_ZoY6oFcCEfG-WqRER0mjbQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_m9Pb4VcCEfG-WqRER0mjbQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_m9Pb4lcCEfG-WqRER0mjbQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_tT_GFFcDEfG-WqRER0mjbQ" target="_tT-fAFcDEfG-WqRER0mjbQ" source="_eEZy8FcCEfG-WqRER0mjbQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_tT_GFVcDEfG-WqRER0mjbQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_tT_GFlcDEfG-WqRER0mjbQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_Ko-xm1cBEfG-WqRER0mjbQ" documentation="Este es un ejemplo de actor que está mapeado a cualquier usuario de la organización ACME" name="Employee actor" initiator="true"/>
      <contract xmi:type="process:Contract" xmi:id="_Ko-xnFcBEfG-WqRER0mjbQ"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_Ko-xnVcBEfG-WqRER0mjbQ">
        <name xmi:type="expression:Expression" xmi:id="_Ko-xnlcBEfG-WqRER0mjbQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_Ko-xn1cBEfG-WqRER0mjbQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_Ko-xoFcBEfG-WqRER0mjbQ">
        <name xmi:type="expression:Expression" xmi:id="_Ko-xoVcBEfG-WqRER0mjbQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_Ko-xolcBEfG-WqRER0mjbQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_Ko-xo1cBEfG-WqRER0mjbQ">
        <name xmi:type="expression:Expression" xmi:id="_Ko-xpFcBEfG-WqRER0mjbQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_Ko-xpVcBEfG-WqRER0mjbQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_Ko-xplcBEfG-WqRER0mjbQ">
        <name xmi:type="expression:Expression" xmi:id="_Ko-xp1cBEfG-WqRER0mjbQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_Ko-xqFcBEfG-WqRER0mjbQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_Ko-xqVcBEfG-WqRER0mjbQ">
        <name xmi:type="expression:Expression" xmi:id="_Ko-xqlcBEfG-WqRER0mjbQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_Ko-xq1cBEfG-WqRER0mjbQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_Ko-xrFcBEfG-WqRER0mjbQ" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_Ko-xrVcBEfG-WqRER0mjbQ" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_Ko-xrlcBEfG-WqRER0mjbQ" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_Ko-xr1cBEfG-WqRER0mjbQ" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_Ko-xsFcBEfG-WqRER0mjbQ" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_Ko-xsVcBEfG-WqRER0mjbQ" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_Ko-xslcBEfG-WqRER0mjbQ" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_Ko-xs1cBEfG-WqRER0mjbQ" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_Ko-xtFcBEfG-WqRER0mjbQ" name="Business_Object"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_Ko-xtVcBEfG-WqRER0mjbQ" type="Process" element="_Ko-xgFcBEfG-WqRER0mjbQ" name="MiDiagrama" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_Ko-xtlcBEfG-WqRER0mjbQ" type="2007" element="_Ko-xgVcBEfG-WqRER0mjbQ">
      <children xmi:type="notation:DecorationNode" xmi:id="_Ko-xt1cBEfG-WqRER0mjbQ" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_Ko-xuFcBEfG-WqRER0mjbQ" type="7001">
        <children xmi:type="notation:Node" xmi:id="_Ko-xuVcBEfG-WqRER0mjbQ" type="3007" element="_Ko-xglcBEfG-WqRER0mjbQ">
          <children xmi:type="notation:DecorationNode" xmi:id="_Ko-xulcBEfG-WqRER0mjbQ" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_Ko-xu1cBEfG-WqRER0mjbQ" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_Ko-xvFcBEfG-WqRER0mjbQ" type="3005" element="_Ko-xh1cBEfG-WqRER0mjbQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_Ko-xvVcBEfG-WqRER0mjbQ" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Ko-xvlcBEfG-WqRER0mjbQ" x="206" y="123"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Ko-xv1cBEfG-WqRER0mjbQ" type="3002" element="_Ko-xg1cBEfG-WqRER0mjbQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_Ko-xwFcBEfG-WqRER0mjbQ" type="5024">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_Ko-xwVcBEfG-WqRER0mjbQ" x="1" y="15"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Ko-xwlcBEfG-WqRER0mjbQ" x="86" y="138"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_LVpNwFcCEfG-WqRER0mjbQ" type="3008" element="_LVmxgFcCEfG-WqRER0mjbQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_LVpNwlcCEfG-WqRER0mjbQ" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_LVpNw1cCEfG-WqRER0mjbQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_LVpNwVcCEfG-WqRER0mjbQ" x="380" y="131" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_ZoaIwFcCEfG-WqRER0mjbQ" type="3027" element="_ZoY6oFcCEfG-WqRER0mjbQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_ZoaIwlcCEfG-WqRER0mjbQ" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_ZoaIwVcCEfG-WqRER0mjbQ" x="556" y="63" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_eEhHuFcCEfG-WqRER0mjbQ" type="3027" element="_eEZy8FcCEfG-WqRER0mjbQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_eEhHulcCEfG-WqRER0mjbQ" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_eEhHuVcCEfG-WqRER0mjbQ" x="566" y="186"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_m9LKdFcCEfG-WqRER0mjbQ" type="3003" element="_m9LKcFcCEfG-WqRER0mjbQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_m9LKdlcCEfG-WqRER0mjbQ" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_m9LKd1cCEfG-WqRER0mjbQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_m9LKdVcCEfG-WqRER0mjbQ" x="782" y="78"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_tT_GEFcDEfG-WqRER0mjbQ" type="3003" element="_tT-fAFcDEfG-WqRER0mjbQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_tT_GElcDEfG-WqRER0mjbQ" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_tT_GE1cDEfG-WqRER0mjbQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_tT_GEVcDEfG-WqRER0mjbQ" x="782" y="196"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_Ko-xw1cBEfG-WqRER0mjbQ"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_Ko-xxFcBEfG-WqRER0mjbQ" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_Ko-xxVcBEfG-WqRER0mjbQ"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_Ko-xxlcBEfG-WqRER0mjbQ"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Ko-xx1cBEfG-WqRER0mjbQ" x="53" y="10" width="1292" height="296"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_Ko-xyFcBEfG-WqRER0mjbQ"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_Ko-xyVcBEfG-WqRER0mjbQ" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_Ko-xylcBEfG-WqRER0mjbQ"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_Ko-xy1cBEfG-WqRER0mjbQ"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Ko-xzFcBEfG-WqRER0mjbQ" width="1320" height="250"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_Ko-xzVcBEfG-WqRER0mjbQ"/>
    <edges xmi:type="notation:Connector" xmi:id="_Ko-xzlcBEfG-WqRER0mjbQ" type="4001" element="_Ko-xmFcBEfG-WqRER0mjbQ" source="_Ko-xv1cBEfG-WqRER0mjbQ" target="_Ko-xvFcBEfG-WqRER0mjbQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Ko-xz1cBEfG-WqRER0mjbQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Ko-x0FcBEfG-WqRER0mjbQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Ko-x0VcBEfG-WqRER0mjbQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Ko-x0lcBEfG-WqRER0mjbQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_KAfYsFcCEfG-WqRER0mjbQ" type="4001" element="_KAdjgFcCEfG-WqRER0mjbQ" source="_Ko-xvFcBEfG-WqRER0mjbQ" target="_LVpNwFcCEfG-WqRER0mjbQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_KAfYs1cCEfG-WqRER0mjbQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_KAfYtFcCEfG-WqRER0mjbQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_KAfYsVcCEfG-WqRER0mjbQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_KAfYslcCEfG-WqRER0mjbQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Zoav01cCEfG-WqRER0mjbQ" type="4001" element="_Zoav0FcCEfG-WqRER0mjbQ" source="_LVpNwFcCEfG-WqRER0mjbQ" target="_ZoaIwFcCEfG-WqRER0mjbQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Zoav1lcCEfG-WqRER0mjbQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Zoav11cCEfG-WqRER0mjbQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Zoav1FcCEfG-WqRER0mjbQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Zoav1VcCEfG-WqRER0mjbQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_eEhuw1cCEfG-WqRER0mjbQ" type="4001" element="_eEhuwFcCEfG-WqRER0mjbQ" source="_LVpNwFcCEfG-WqRER0mjbQ" target="_eEhHuFcCEfG-WqRER0mjbQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_eEhuxlcCEfG-WqRER0mjbQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_eEhux1cCEfG-WqRER0mjbQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_eEhuxFcCEfG-WqRER0mjbQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_eEhuxVcCEfG-WqRER0mjbQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_m9Pb41cCEfG-WqRER0mjbQ" type="4001" element="_m9Pb4FcCEfG-WqRER0mjbQ" source="_ZoaIwFcCEfG-WqRER0mjbQ" target="_m9LKdFcCEfG-WqRER0mjbQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_m9Pb5lcCEfG-WqRER0mjbQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_m9Pb51cCEfG-WqRER0mjbQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_m9Pb5FcCEfG-WqRER0mjbQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_m9Pb5VcCEfG-WqRER0mjbQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_tUBiUFcDEfG-WqRER0mjbQ" type="4001" element="_tT_GFFcDEfG-WqRER0mjbQ" source="_eEhHuFcCEfG-WqRER0mjbQ" target="_tT_GEFcDEfG-WqRER0mjbQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_tUBiU1cDEfG-WqRER0mjbQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_tUBiVFcDEfG-WqRER0mjbQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_tUBiUVcDEfG-WqRER0mjbQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_tUBiUlcDEfG-WqRER0mjbQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
