<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:decision="http://www.bonitasoft.org/ns/bpm/process/decision" xmlns:expression="http://www.bonitasoft.org/ns/bpm/expression" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.3/notation" xmlns:process="http://www.bonitasoft.org/ns/bpm/process">
  <process:MainProcess xmi:id="_oFzUgFcEEfG-WqRER0mjbQ" name="DiagramaSolicitudVacaciones" version="1.1" bonitaModelVersion="8">
    <elements xmi:type="process:Pool" xmi:id="_oFzUgVcEEfG-WqRER0mjbQ" name="Pool" version="1.1">
      <elements xmi:type="process:Lane" xmi:id="_oFzUglcEEfG-WqRER0mjbQ" name="Empleado (lane) " actor="_oFzUyFcEEfG-WqRER0mjbQ">
        <elements xmi:type="process:StartEvent" xmi:id="_oFzUg1cEEfG-WqRER0mjbQ" name="IniIngresar solicitud" outgoing="_oFzUtlcEEfG-WqRER0mjbQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_oFzUhFcEEfG-WqRER0mjbQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_oFzUhVcEEfG-WqRER0mjbQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_oFzUhlcEEfG-WqRER0mjbQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_oFzUh1cEEfG-WqRER0mjbQ" name="Validar solicitud" outgoing="_oFzUuVcEEfG-WqRER0mjbQ _w-o9fFcEEfG-WqRER0mjbQ" incoming="_oFzUtlcEEfG-WqRER0mjbQ" overrideActorsOfTheLane="false">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_oFzUiFcEEfG-WqRER0mjbQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_oFzUiVcEEfG-WqRER0mjbQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_oFzUilcEEfG-WqRER0mjbQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_oFzUi1cEEfG-WqRER0mjbQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_oFzUjFcEEfG-WqRER0mjbQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_oFzUjVcEEfG-WqRER0mjbQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_oFzUjlcEEfG-WqRER0mjbQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_oFzUj1cEEfG-WqRER0mjbQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <BoundaryIntermediateEvents xmi:type="process:NonInterruptingBoundaryTimerEvent" xmi:id="_r5Ex0FcEEfG-WqRER0mjbQ" name="Enviar recordatorio después de 5s.">
            <condition xmi:type="expression:Expression" xmi:id="_9RxtkFcFEfG-WqRER0mjbQ" name="00:00:05" content="5000L" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Long"/>
          </BoundaryIntermediateEvents>
          <formMapping xmi:type="process:FormMapping" xmi:id="_oFzUkFcEEfG-WqRER0mjbQ">
            <targetForm xmi:type="expression:Expression" xmi:id="_oFzUkVcEEfG-WqRER0mjbQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_oFzUklcEEfG-WqRER0mjbQ"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_oFzUk1cEEfG-WqRER0mjbQ" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_oFzUlFcEEfG-WqRER0mjbQ" name="¿Solicitud aprobada?" outgoing="_oFzUvFcEEfG-WqRER0mjbQ _oFzUv1cEEfG-WqRER0mjbQ" incoming="_oFzUuVcEEfG-WqRER0mjbQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_oFzUlVcEEfG-WqRER0mjbQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_oFzUllcEEfG-WqRER0mjbQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_oFzUl1cEEfG-WqRER0mjbQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_oFzUmFcEEfG-WqRER0mjbQ" name="Notificar aprobación" outgoing="_oFzUwlcEEfG-WqRER0mjbQ" incoming="_oFzUvFcEEfG-WqRER0mjbQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_oFzUmVcEEfG-WqRER0mjbQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_oFzUmlcEEfG-WqRER0mjbQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_oFzUm1cEEfG-WqRER0mjbQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_oFzUnFcEEfG-WqRER0mjbQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_oFzUnVcEEfG-WqRER0mjbQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_oFzUnlcEEfG-WqRER0mjbQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_oFzUn1cEEfG-WqRER0mjbQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_oFzUoFcEEfG-WqRER0mjbQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_oFzUoVcEEfG-WqRER0mjbQ" name="Notificar rechazo" outgoing="_oFzUxVcEEfG-WqRER0mjbQ" incoming="_oFzUv1cEEfG-WqRER0mjbQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_oFzUolcEEfG-WqRER0mjbQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_oFzUo1cEEfG-WqRER0mjbQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_oFzUpFcEEfG-WqRER0mjbQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_oFzUpVcEEfG-WqRER0mjbQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_oFzUplcEEfG-WqRER0mjbQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_oFzUp1cEEfG-WqRER0mjbQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_oFzUqFcEEfG-WqRER0mjbQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_oFzUqVcEEfG-WqRER0mjbQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_oFzUqlcEEfG-WqRER0mjbQ" name="Fin - Solicitud aprobada" incoming="_oFzUwlcEEfG-WqRER0mjbQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_oFzUq1cEEfG-WqRER0mjbQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_oFzUrFcEEfG-WqRER0mjbQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_oFzUrVcEEfG-WqRER0mjbQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_oFzUrlcEEfG-WqRER0mjbQ" name="Fin - Solicitud rechazada" incoming="_oFzUxVcEEfG-WqRER0mjbQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_oFzUr1cEEfG-WqRER0mjbQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_oFzUsFcEEfG-WqRER0mjbQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_oFzUsVcEEfG-WqRER0mjbQ" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_w-o9cFcEEfG-WqRER0mjbQ" name="Enviar recordatorio de validación" outgoing="__cTg4lcEEfG-WqRER0mjbQ" incoming="_w-o9fFcEEfG-WqRER0mjbQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_w-o9clcEEfG-WqRER0mjbQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_w-o9cVcEEfG-WqRER0mjbQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_w-o9c1cEEfG-WqRER0mjbQ" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_w-o9dFcEEfG-WqRER0mjbQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_w-o9dVcEEfG-WqRER0mjbQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_w-o9dlcEEfG-WqRER0mjbQ" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_w-o9eFcEEfG-WqRER0mjbQ" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_w-o9d1cEEfG-WqRER0mjbQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="__cK-AFcEEfG-WqRER0mjbQ" name="Fin - recordatorio enviado" incoming="__cTg4lcEEfG-WqRER0mjbQ">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="__cK-AlcEEfG-WqRER0mjbQ" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="__cK-AVcEEfG-WqRER0mjbQ" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="__cK-A1cEEfG-WqRER0mjbQ" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <formMapping xmi:type="process:FormMapping" xmi:id="_oFzUslcEEfG-WqRER0mjbQ">
        <targetForm xmi:type="expression:Expression" xmi:id="_oFzUs1cEEfG-WqRER0mjbQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_oFzUtFcEEfG-WqRER0mjbQ">
        <targetForm xmi:type="expression:Expression" xmi:id="_oFzUtVcEEfG-WqRER0mjbQ" name="" content="" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_oFzUtlcEEfG-WqRER0mjbQ" target="_oFzUh1cEEfG-WqRER0mjbQ" source="_oFzUg1cEEfG-WqRER0mjbQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_oFzUt1cEEfG-WqRER0mjbQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_oFzUuFcEEfG-WqRER0mjbQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_oFzUuVcEEfG-WqRER0mjbQ" target="_oFzUlFcEEfG-WqRER0mjbQ" source="_oFzUh1cEEfG-WqRER0mjbQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_oFzUulcEEfG-WqRER0mjbQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_oFzUu1cEEfG-WqRER0mjbQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_oFzUvFcEEfG-WqRER0mjbQ" name="si" target="_oFzUmFcEEfG-WqRER0mjbQ" source="_oFzUlFcEEfG-WqRER0mjbQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_oFzUvVcEEfG-WqRER0mjbQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_oFzUvlcEEfG-WqRER0mjbQ" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_oFzUv1cEEfG-WqRER0mjbQ" name="No" target="_oFzUoVcEEfG-WqRER0mjbQ" source="_oFzUlFcEEfG-WqRER0mjbQ" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_oFzUwFcEEfG-WqRER0mjbQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_oFzUwVcEEfG-WqRER0mjbQ" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_oFzUwlcEEfG-WqRER0mjbQ" target="_oFzUqlcEEfG-WqRER0mjbQ" source="_oFzUmFcEEfG-WqRER0mjbQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_oFzUw1cEEfG-WqRER0mjbQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_oFzUxFcEEfG-WqRER0mjbQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_oFzUxVcEEfG-WqRER0mjbQ" target="_oFzUrlcEEfG-WqRER0mjbQ" source="_oFzUoVcEEfG-WqRER0mjbQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_oFzUxlcEEfG-WqRER0mjbQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_oFzUx1cEEfG-WqRER0mjbQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_w-o9fFcEEfG-WqRER0mjbQ" target="_w-o9cFcEEfG-WqRER0mjbQ" source="_oFzUh1cEEfG-WqRER0mjbQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_w-o9fVcEEfG-WqRER0mjbQ"/>
        <condition xmi:type="expression:Expression" xmi:id="_w-o9flcEEfG-WqRER0mjbQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="__cTg4lcEEfG-WqRER0mjbQ" target="__cK-AFcEEfG-WqRER0mjbQ" source="_w-o9cFcEEfG-WqRER0mjbQ">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="__cTg41cEEfG-WqRER0mjbQ"/>
        <condition xmi:type="expression:Expression" xmi:id="__cTg5FcEEfG-WqRER0mjbQ" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_oFzUyFcEEfG-WqRER0mjbQ" documentation="Este es un ejemplo de actor que está mapeado a cualquier usuario de la organización ACME" name="Employee actor" initiator="true"/>
      <contract xmi:type="process:Contract" xmi:id="_oFzUyVcEEfG-WqRER0mjbQ"/>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_oFzUylcEEfG-WqRER0mjbQ">
        <name xmi:type="expression:Expression" xmi:id="_oFzUy1cEEfG-WqRER0mjbQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_oFzUzFcEEfG-WqRER0mjbQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_oFzUzVcEEfG-WqRER0mjbQ">
        <name xmi:type="expression:Expression" xmi:id="_oFzUzlcEEfG-WqRER0mjbQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_oFzUz1cEEfG-WqRER0mjbQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_oFzU0FcEEfG-WqRER0mjbQ">
        <name xmi:type="expression:Expression" xmi:id="_oFzU0VcEEfG-WqRER0mjbQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_oFzU0lcEEfG-WqRER0mjbQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_oFzU01cEEfG-WqRER0mjbQ">
        <name xmi:type="expression:Expression" xmi:id="_oFzU1FcEEfG-WqRER0mjbQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_oFzU1VcEEfG-WqRER0mjbQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_oFzU1lcEEfG-WqRER0mjbQ">
        <name xmi:type="expression:Expression" xmi:id="_oFzU11cEEfG-WqRER0mjbQ" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_oFzU2FcEEfG-WqRER0mjbQ" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_oFzU2VcEEfG-WqRER0mjbQ" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_oFzU2lcEEfG-WqRER0mjbQ" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_oFzU21cEEfG-WqRER0mjbQ" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_oFzU3FcEEfG-WqRER0mjbQ" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_oFzU3VcEEfG-WqRER0mjbQ" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_oFzU3lcEEfG-WqRER0mjbQ" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_oFzU31cEEfG-WqRER0mjbQ" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_oFzU4FcEEfG-WqRER0mjbQ" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_oFzU4VcEEfG-WqRER0mjbQ" name="Business_Object"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_oFzU4lcEEfG-WqRER0mjbQ" type="Process" element="_oFzUgFcEEfG-WqRER0mjbQ" name="MiDiagrama" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_oFzU41cEEfG-WqRER0mjbQ" type="2007" element="_oFzUgVcEEfG-WqRER0mjbQ">
      <children xmi:type="notation:DecorationNode" xmi:id="_oFzU5FcEEfG-WqRER0mjbQ" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_oFzU5VcEEfG-WqRER0mjbQ" type="7001">
        <children xmi:type="notation:Node" xmi:id="_oFzU5lcEEfG-WqRER0mjbQ" type="3007" element="_oFzUglcEEfG-WqRER0mjbQ">
          <children xmi:type="notation:DecorationNode" xmi:id="_oFzU51cEEfG-WqRER0mjbQ" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_oFzU6FcEEfG-WqRER0mjbQ" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_oFzU6VcEEfG-WqRER0mjbQ" type="3005" element="_oFzUh1cEEfG-WqRER0mjbQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_oFzU6lcEEfG-WqRER0mjbQ" type="5005"/>
              <children xmi:type="notation:Shape" xmi:id="_r5HOEFcEEfG-WqRER0mjbQ" type="3064" element="_r5Ex0FcEEfG-WqRER0mjbQ" fontName="Segoe UI">
                <children xmi:type="notation:DecorationNode" xmi:id="_r5IcMFcEEfG-WqRER0mjbQ" type="5094">
                  <layoutConstraint xmi:type="notation:Location" xmi:id="_r5IcMVcEEfG-WqRER0mjbQ" y="5"/>
                </children>
                <layoutConstraint xmi:type="notation:Bounds" xmi:id="_r5HOEVcEEfG-WqRER0mjbQ" x="16" y="42"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_oFzU61cEEfG-WqRER0mjbQ" x="206" y="123"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_oFzU7FcEEfG-WqRER0mjbQ" type="3002" element="_oFzUg1cEEfG-WqRER0mjbQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_oFzU7VcEEfG-WqRER0mjbQ" type="5024">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_oFzU7lcEEfG-WqRER0mjbQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_oFzU71cEEfG-WqRER0mjbQ" x="86" y="138"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_oFzU8FcEEfG-WqRER0mjbQ" type="3008" element="_oFzUlFcEEfG-WqRER0mjbQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_oFzU8VcEEfG-WqRER0mjbQ" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_oFzU8lcEEfG-WqRER0mjbQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_oFzU81cEEfG-WqRER0mjbQ" x="380" y="131" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_oFzU9FcEEfG-WqRER0mjbQ" type="3027" element="_oFzUmFcEEfG-WqRER0mjbQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_oFzU9VcEEfG-WqRER0mjbQ" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_oFzU9lcEEfG-WqRER0mjbQ" x="556" y="63" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_oFzU91cEEfG-WqRER0mjbQ" type="3027" element="_oFzUoVcEEfG-WqRER0mjbQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_oFzU-FcEEfG-WqRER0mjbQ" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_oFzU-VcEEfG-WqRER0mjbQ" x="566" y="186"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_oFzU-lcEEfG-WqRER0mjbQ" type="3003" element="_oFzUqlcEEfG-WqRER0mjbQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_oFzU-1cEEfG-WqRER0mjbQ" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_oFzU_FcEEfG-WqRER0mjbQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_oFzU_VcEEfG-WqRER0mjbQ" x="782" y="78"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_oFzU_lcEEfG-WqRER0mjbQ" type="3003" element="_oFzUrlcEEfG-WqRER0mjbQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_oFzU_1cEEfG-WqRER0mjbQ" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_oFzVAFcEEfG-WqRER0mjbQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_oFzVAVcEEfG-WqRER0mjbQ" x="782" y="196"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_w-o9eVcEEfG-WqRER0mjbQ" type="3027" element="_w-o9cFcEEfG-WqRER0mjbQ" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_w-o9e1cEEfG-WqRER0mjbQ" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_w-o9elcEEfG-WqRER0mjbQ" x="179" y="252" width="154" height="77"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="__cK-BFcEEfG-WqRER0mjbQ" type="3003" element="__cK-AFcEEfG-WqRER0mjbQ" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="__cTg4FcEEfG-WqRER0mjbQ" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="__cTg4VcEEfG-WqRER0mjbQ" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="__cK-BVcEEfG-WqRER0mjbQ" x="406" y="280"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_oFzVAlcEEfG-WqRER0mjbQ"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_oFzVA1cEEfG-WqRER0mjbQ" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_oFzVBFcEEfG-WqRER0mjbQ"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_oFzVBVcEEfG-WqRER0mjbQ"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_oFzVBlcEEfG-WqRER0mjbQ" x="53" y="10" width="1292" height="403"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_oFzVB1cEEfG-WqRER0mjbQ"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_oFzVCFcEEfG-WqRER0mjbQ" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_oFzVCVcEEfG-WqRER0mjbQ"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_oFzVClcEEfG-WqRER0mjbQ"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_oFzVC1cEEfG-WqRER0mjbQ" width="1320" height="250"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_oFzVDFcEEfG-WqRER0mjbQ"/>
    <edges xmi:type="notation:Connector" xmi:id="_oFzVDVcEEfG-WqRER0mjbQ" type="4001" element="_oFzUtlcEEfG-WqRER0mjbQ" source="_oFzU7FcEEfG-WqRER0mjbQ" target="_oFzU6VcEEfG-WqRER0mjbQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_oFzVDlcEEfG-WqRER0mjbQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_oFzVD1cEEfG-WqRER0mjbQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_oFzVEFcEEfG-WqRER0mjbQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_oFzVEVcEEfG-WqRER0mjbQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_oFzVElcEEfG-WqRER0mjbQ" type="4001" element="_oFzUuVcEEfG-WqRER0mjbQ" source="_oFzU6VcEEfG-WqRER0mjbQ" target="_oFzU8FcEEfG-WqRER0mjbQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_oFzVE1cEEfG-WqRER0mjbQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_oFzVFFcEEfG-WqRER0mjbQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_oFzVFVcEEfG-WqRER0mjbQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_oFzVFlcEEfG-WqRER0mjbQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_oFzVF1cEEfG-WqRER0mjbQ" type="4001" element="_oFzUvFcEEfG-WqRER0mjbQ" source="_oFzU8FcEEfG-WqRER0mjbQ" target="_oFzU9FcEEfG-WqRER0mjbQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_oFzVGFcEEfG-WqRER0mjbQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_oFzVGVcEEfG-WqRER0mjbQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_oFzVGlcEEfG-WqRER0mjbQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_oFzVG1cEEfG-WqRER0mjbQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_oFzVHFcEEfG-WqRER0mjbQ" type="4001" element="_oFzUv1cEEfG-WqRER0mjbQ" source="_oFzU8FcEEfG-WqRER0mjbQ" target="_oFzU91cEEfG-WqRER0mjbQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_oFzVHVcEEfG-WqRER0mjbQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_oFzVHlcEEfG-WqRER0mjbQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_oFzVH1cEEfG-WqRER0mjbQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_oFzVIFcEEfG-WqRER0mjbQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_oFzVIVcEEfG-WqRER0mjbQ" type="4001" element="_oFzUwlcEEfG-WqRER0mjbQ" source="_oFzU9FcEEfG-WqRER0mjbQ" target="_oFzU-lcEEfG-WqRER0mjbQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_oFzVIlcEEfG-WqRER0mjbQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_oFzVI1cEEfG-WqRER0mjbQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_oFzVJFcEEfG-WqRER0mjbQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_oFzVJVcEEfG-WqRER0mjbQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_oFzVJlcEEfG-WqRER0mjbQ" type="4001" element="_oFzUxVcEEfG-WqRER0mjbQ" source="_oFzU91cEEfG-WqRER0mjbQ" target="_oFzU_lcEEfG-WqRER0mjbQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_oFzVJ1cEEfG-WqRER0mjbQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_oFzVKFcEEfG-WqRER0mjbQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_oFzVKVcEEfG-WqRER0mjbQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_oFzVKlcEEfG-WqRER0mjbQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_w-o9f1cEEfG-WqRER0mjbQ" type="4001" element="_w-o9fFcEEfG-WqRER0mjbQ" source="_oFzU6VcEEfG-WqRER0mjbQ" target="_w-o9eVcEEfG-WqRER0mjbQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_w-o9glcEEfG-WqRER0mjbQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_w-o9g1cEEfG-WqRER0mjbQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_w-o9gFcEEfG-WqRER0mjbQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_w-o9gVcEEfG-WqRER0mjbQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="__cUH8FcEEfG-WqRER0mjbQ" type="4001" element="__cTg4lcEEfG-WqRER0mjbQ" source="_w-o9eVcEEfG-WqRER0mjbQ" target="__cK-BFcEEfG-WqRER0mjbQ" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="__cUH81cEEfG-WqRER0mjbQ" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="__cUH9FcEEfG-WqRER0mjbQ" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="__cUH8VcEEfG-WqRER0mjbQ" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="__cUH8lcEEfG-WqRER0mjbQ" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
